language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t 9972899815/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true 9972899815/docker-react npm run test
