version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /react/node_modules
      - ./:/react
    restart: always
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - CHOKIDAR-USEPOLLING=true
